### ISSUE TITLE
Support natural sorting of keys.

### ISSUE THREAD

**Issue by gunn** [d3/d3-collection#13]
Currently `nest.sortKeys(comparator)` only sorts keys as strings.

It seems like this often won't give the desired behaviour. For instance it will fail on dates and numbers with more than one digit.

Example code:
```javascript
const nest = d3.nest()
    .key(d=> d.date)
    .sortKeys(d3.descending)
    .entries(itemsWithDates)
```

Full running example:
http://bl.ocks.org/gunn/49919c316ebea97d56c31955a607f11f

**Comment by mbostock** [comment]
Keys are always coerced to strings, so this is the expected behavior. Per the documentation for [*nest*.key](https://github.com/d3/d3-collection/blob/master/README.md#nest_key), emphasis added:

> The *key* function will be invoked for each element in the input array and **must return a string identifier** to assign the element to its group.

Any return value that is not a string is coerced to a string.

**Comment by gunn** [comment]
Excellent response time.
I understand that it's expected and not a bug. It seems like it leaves `sortKeys` not very useful if it can't sort numbers though. Surely this will be a common problem?

**Comment by mbostock** [comment]
You can either use a string that sorts lexicographically in the desired order (for example, formatting your dates appropriately with [d3-time-format](https://github.com/d3/d3-time-format)), or you can coerce back to a number in your comparator function. For example, assuming that *d*.date is a Date object and you want to group by unique dates (milliseconds):

```js
const nest = d3.nest()
    .key(d => +d.date)
    .sortKeys((a, b) => a - b)
    .entries(data);
```

**Comment by gunn** [comment]
Okay workarounds for now then. I suppose this might change in the future with #11. Thank you Mike.

**Comment by mbostock** [comment]
Exactly.
