### ISSUE TITLE
Nest: individual key sorting

### ISSUE THREAD

**Issue by twobit** [d3/d3-collection#2]
Sometimes it's necessary to sort keys differently. Currently, only one sort is applied to all keys. I'm thinking the `key` function could accept an optional sort function:

```
d3.nest()
  .key(d => d.region, d3.ascending)
  .key(d => d.country, d3.descending)
  .entries(data)
```

Would be very useful for something like a pivot table.

**Comment by mbostock** [comment]
The sort function only applies to the most-recently registered key. So your example should look like this:

``` js
d3.nest()
    .key(d => d.region).sortKeys(d3.ascending)
    .key(d => d.country).sortKeys(d3.descending)
    .entries(data)
```

I’ve made the documentation a bit more explicit.
