### ISSUE TITLE
Feature Request - same level nesting by multiple key

### ISSUE THREAD

**Issue by bumbeishvili** [d3/d3-collection#24]
[See this interactive notebook to display problem](https://beta.observablehq.com/@bumbeishvili/playing-with-d3-nest-source)

Suppose we have dataset like this
 ```javascript
var arr = [
  {name: "jim",   amount: "34.0",   date: "11/12/2015"},
  {name: "carl",  amount: "120.11", date: "11/12/2015"},
  {name: "stacy", amount: "12.01",  date: "01/04/2016"},
  {name: "stacy", amount: "34.05",  date: "01/04/2016"}
]
```

Would be good if we have possibility to nest by multiple key at one level

So, if we would try 
```javascript
expensesByNameAndDate = d3.nest()
  .keys(["name","date"])  // keys , not  key
  .entries(expenses)
```

We would get 

```javascript
[
{
  "key": { "name": "jim","date": "11/12/2015"},
  "values": [{"name": "jim","amount": "34.0","date": "11/12/2015"}]
},
{ "key": {"name": "carl","date": "11/12/2015"},
   "values": [{"name": "carl","amount": "120.11","date": "11/12/2015"}]
},
{  "key": {"name": "stacy","date": "01/04/2016"},
  "values": [{"name": "stacy","amount": "12.01","date": "01/04/2016"},{"name": "stacy","amount": "34.05","date": "01/04/2016"}]
  }
]
```

Possible overloads for keys func

1.  ` .keys(["name","date"])`   
2.   ` .keys([d=>d.name,d=>d.date])`

**Comment by mbostock** [comment]
JavaScript’s built-in Map class doesn’t let you define equality, so I don’t think there’s a good way of doing this other than nested maps, which are now supported in d3-array 2.0 using group (and rollup).

https://beta.observablehq.com/@d3/d3-array-2-0
