### ISSUE TITLE
Custom key, values field names for the nest()

### ISSUE THREAD

**Issue by nyurik** [d3/d3-collection#25]
[nest](https://github.com/d3/d3-collection#nests) hardcodes `key` and `values`.  If not too difficult, please support custom field names, as this would make [this Vega's issue](https://github.com/vega/vega/issues/1241#issuecomment-383236342) much easier to solve.  Thanks!

BTW, I think this has benefit to other users because it simplifies result examination in case when original data also contains `key` or `values` fields, and the caller needs to find which objects were generated.

**Comment by mbostock** [comment]
Thanks for the suggestion and pull request. However, I don’t understand why it is useful to allow these names to be specified by the caller (other than the linked Vega issue, which seems to be a Vega feature request rather than an issue with d3.nest’s API), especially given that the caller could map the return value of *nest*.entries if different names are desired.

**Comment by nyurik** [comment]
@mbostock nest() mixes together user's data and the generated data in the output. If input data already contains `key` or `values` fields, and I had to analyze the output, it might be more difficult to tell apart original vs generated.

How about a different implementation:  a `factory(key, values)` that gets called by nest to create new elements?  By default it will be  `(key, values) => ({ key, values })`, but user would be able to supply a different implementation?

**Comment by mbostock** [comment]
*nest*.entries returns a nested structure dictated by how many keys you define using *nest*.key; there is no ambiguity or mixing of input data fields with the {key, values} entries.

**Comment by nyurik** [comment]
@mbostock understood.  Would my alternative idea work though?  Because there could be a lot of cases when you want to customize the creation of the new nodes?

**Comment by nyurik** [comment]
@mbostock here's a PR for a more generic approach - a factory method to customize new node creation. With this approach, users won't need to do complex post-processing iteration of the whole tree if they need to calculate sub-aggregations on the portion of the tree, or if they want to attach additional values to each node.  What's more, they might not even want to construct the result tree at all - making nest() into an iteration system instead of an object generation.  https://github.com/d3/d3-collection/pull/27
