### ISSUE TITLE
nest.rollup should create {key, value} for leaf entries.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-collection#3]
This makes it easier to disambiguate leaf nodes from parent nodes.

**Comment by mbostock** [comment]
Perhaps nest.entries should create {key, children} by default, too. Then it would be default-compatible with [d3.hierarchy](https://github.com/d3/d3-hierarchy#hierarchy).

**Comment by syntagmatic** [comment]
I think it's best to keep the behavior of d3.nest as it is-- at least key/values for the internal node keys. It's a simple, successful function with many examples and tutorials out there.

The referenced issue could resolved with a new convenience function in d3-hierarchy that has an API similar d3.nest but returns a hierarchy object. The new function would be a sibling to `stratify`.

**Comment by mbostock** [comment]
I don’t want to introduce a new operator; that’s a pretty big addition to the API when there’s already a reasonable way to turn the result of _nest_.entries into a d3.hierarchy. We’re just talking about turning this:

``` js
var root = d3.hierarchy({values: nest.entries(data)}, function(d) { return d.values; })
    .sum(function(d) { return d.values; });
```

Into this:

``` js
var root = d3.hierarchy({children: nest.entries(data)})
    .sum(function(d) { return d.value; });
```

Or, if we just change the behavior of _nest_.rollup and don’t adopt _entry_.children:

``` js
var root = d3.hierarchy({values: nest.entries(data)}, function(d) { return d.values; })
    .sum(function(d) { return d.value; });
```

Name changes are the most trivial of incompatibilities. We shouldn’t needlessly rename things, but if changing _entry_.values to _entry_.children makes things easier, it might be worth it. Certainly there are a lot of other API changes in D3 4.0 that I believe are worth it; we shouldn’t needlessly bind ourselves to past API decisions if we’ve learned something since.

It is interesting to consider whether d3.nest should return a d3.hierarchy instance directly. That would suggest moving d3.nest to the d3-hierarchy module, or perhaps better, moving d3.hierarchy and d3.stratify into d3-collection (since these are just operations on data and not hierarchical layouts). That would offer some nice improvements, like addressing #4 because d3.hierarchy provides visit methods, but you also lose something because nests are specialized hierarchies where each child is uniquely identified by a string key. It’s sometimes convenient to represent them as nested maps.

So, I feel like it’s worth considering renaming _entry_.values to _entry_.children (and having _nest_.rollup replace _entry_.children with _entry_.value), but I’m not currently in favor of more substantial changes.

**Comment by mbostock** [comment]
I’ve implemented both approaches in #6 and #7. I guess I’m leaning towards #6 to be conservative now.

**Comment by mbostock** [comment]
Merged #6.

**Comment by PatriciaW43** [comment]
I'm having problems with d3.nest. Sometimes rollup returns key/value and sometimes key/values. It appears that the first time it is invoked it results in key/values then key/value. This means that the program works correctly the first time but then it returns key/value and fails.

**Comment by mbostock** [comment]
@PatriciaW43 *nest*.rollup always produces leaf entries with *entry*.value rather than *entry*.values. Please see my guide on [reporting an issue](https://gist.github.com/mbostock/370b737ce71bed0749e103b01ce1bfaf).

**Comment by PatriciaW43** [comment]
I wasn't sure how to report an issue so I created a Gist at gist:fe81b673a90a3cd5f32b7aceca9559c0

**Comment by bplmp** [comment]
For me nest.rollup is also producing entry._values_ on leaf entries.

See this example, which is linked from d3-collection's readme: http://bl.ocks.org/phoebebright/raw/3176159/

    var nested_data = d3.nest()
    .key(function(d) { return d.status; })
    .key(function(d) { return d.priority; })
    .rollup(function(leaves) { return leaves.length; })
    .entries(csv_data);

Returns:

    [
       {
          "key": "Complete",
          "values": [
             {
                "key": "MUST",
                "values": 5
             },
             {
                "key": "SHOULD",
                "values": 5
             },
             {
                "key": "COULD",
                "values": 1
             }
          ]
       },
       {
          "key": "In Progress",
          "values": [
             {
                "key": "MUST",
                "values": 6
             },
             {
                "key": "SHOULD",
                "values": 1
             },
             {
                "key": "WISH",
                "values": 1
             }
          ]
       },
       {
          "key": "Not Started",
          "values": [
             {
                "key": "MUST",
                "values": 9
             },
             {
                "key": "SHOULD",
                "values": 3
             },
             {
                "key": "COULD",
                "values": 3
             },
             {
                "key": "WISH",
                "values": 1
             }
          ]
       }
    ]
