### ISSUE TITLE
Support string as accessor?

### ISSUE THREAD

**Issue by bclinkinbeard** [d3/d3-collection#8]
Since plucking off a single property is likely a very common use case, it would be nice to support simply passing a string so that `d3.set(stuff, 'name')` would be equivalent to `d3.set(stuff, x => x.name)`.

I'd be happy to submit a PR if this is a feature you'd accept.

**Comment by mbostock** [comment]
Sorry, but I do not want to provide this convenience API; I’d rather favor parsimony and use `x => x.name`.
